AspNetMvcExamples/AspNetMvcExamples/Controllers/Session03Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspNetMvcExamples.Controllers
{
    public class LoginDataModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
    public class Session03Controller : Controller
    {
        // GET: Session03
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Razor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult HtmlHelper(LoginDataModel data)
        {
            return View();
        }
        public ActionResult HtmlHelper()
        {
            var cities = new[]
            {
                new { ID = "DANANG", Name = "Chi nhánh Đà Nẵng - 38 Đường Yên Bái" },
                new { ID = "HUE", Name = "Chi nhánh Huế - 5A Đường Phong Châu (Big C)" },
                new { ID = "CANTHO", Name = "Chi nhánh Cần Thơ - 118 Đường 3/2" }
            };
            ViewBag.CityList = new SelectList(cities, "ID", "Name", "HUE");
            ViewBag.City = new SelectList(cities, "ID", "Name", "DANANG");
            return View();
        }
    }
}

AspNetMvcExamples/AspNetMvcExamples/Views/Session03/HtmlHelper.cshtml
@{
    ViewBag.Title = "HtmlHelper";

}

<h2>HtmlHelper</h2>

@Html.TextBox("UserName1", "", new { @class = "form-control", placeholder = "Enter your username" })
@Html.DropDownList("City1", (SelectList)ViewBag.CityList, new { @class = "form-control" })
@Html.DropDownList("City", null, new { @class = "form-control" })

@Html.DropDownList("City9", new List<SelectListItem>() { new SelectListItem() { Text = "Ho Chi Minh", Value = "HCM" } }, new { @class = "form-control" })

@using (Html.BeginForm("HtmlHelper", "Session03", FormMethod.Post))
{
    @Html.TextBox("UserName", "", new { @class = "form-control", placeholder = "Enter your username" })
    @Html.Password("Password", "", new { @class = "form-control", placeholder = "Enter your password" })
    <button type="submit" class="btn btn-primary">Login</button>
}

AspNetMvcExamples/AspNetMvcExamples/Views/Session03/Razor.Mobile.cshtml
@{
    ViewBag.Title = "Razor";
}

<h2>Razor (Mobile)</h2>

AspNetMvcExamples/AspNetMvcExamples/Views/Session03/Razor.cshtml
@{
    ViewBag.Title = "Razor";
}



<h2>Razor</h2>

@{
    var products = new List<string>() { "Laptop", "Mobile"};
    products.Add("Tablet");
    foreach (var s in products)
    {
        <h1>@s</h1>
    }
}

@foreach (var p in products)
{
    var s = "- " + p;
    <h3>@s</h3>
}